---
resources:
- name: spring-gitrepo
  type: git
  source:
    uri: https://github.com/pgoultiaev/spring-docker-concourse.git

jobs:
- name: job-list-files
  public: true
  plan:
  - get: spring-gitrepo
    trigger: true
  - task: list-files
    file: spring-gitrepo/concourse/tasks/list-files.yml

- name: job-unit-test
  public: true
  plan:
  - get: spring-gitrepo
    trigger: true
  - task: unit-test
    file: spring-gitrepo/concourse/tasks/unit-test.yml