---
resources:
- name: spring-gitrepo
  type: git
  check_every: 10s
  source:
    uri: https://github.com/pgoultiaev/spring-docker-concourse.git

jobs:
- name: build-unit-test
  public: true
  plan:
  - get: spring-gitrepo
    trigger: true
  - task: build
    file: spring-gitrepo/concourse/tasks/build.yml
