---
platform: linux

image_resource:
  type: docker-image
  source: {repository: openjdk, tag: 8-jdk-alpine}

inputs:
- name: spring-gitrepo

outputs:
- name: build-output

run:
  path: spring-gitrepo/concourse/scripts/build.sh