---
platform: linux

image_resource:
  type: docker-image
  source: {repository: gradle, tag: 5.3-alpine}

inputs:
  - name: spring-gitrepo

outputs:
  - name: build-jar

run:
  user: root
  path: spring-gitrepo/concourse/scripts/build.sh